name: Frontend

on:
    pull_request:
        branches: ['*']
        types:
            - opened
            - synchronize
            - closed
    push:
        branches: [main]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 16.x
              uses: actions/setup-node@v1
              with:
                  node-version: 16.x
              env:
                  DISCORD_API_TOKEN: ${{ secrets.DISCORD_API_TOKEN }}
            - run: npm ci
            - name: ESLint & StyleLint
              run: npm run lint:ci

    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 16.x
              uses: actions/setup-node@v1
              with:
                  node-version: 16.x
              env:
                  DISCORD_API_TOKEN: ${{ secrets.DISCORD_API_TOKEN }}
            - run: npm ci
            - run: npm run build

    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 16.x
              uses: actions/setup-node@v1
              with:
                  node-version: 16.x
              env:
                  DISCORD_API_TOKEN: ${{ secrets.DISCORD_API_TOKEN }}
            - run: npm ci
            - run: npm test
