name: Frontend

on:
    pull_request:
        branches: ['*']
        types:
            - opened
            - synchronize
            - closed
    push:
        branches: [main]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7
            - uses: actions/setup-node@v7
              with:
                  node-version: 20
            - run: npm ci
            - name: ESLint & StyleLint
              run: npm run lint:ci

    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7
            - uses: actions/setup-node@v7
              with:
                  node-version: 20
            - uses: actions/setup-python@v7
              with:
                  python-version: '3.11'
            - name: Cache thumbnails
              id: cache-thumbnails
              uses: actions/cache@v6
              with:
                  path: .thumb-cache/thumbs
                  key: thumbnails
            - run: npm ci
            - run: npm run build

    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7
            - uses: actions/setup-node@v7
              with:
                  node-version: 20
            - run: npm ci
            - run: npm test

    validate-db:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7
            - uses: actions/setup-node@v7
              with:
                  node-version: 20
            - run: npm ci
            - run: npm run validate-db
